env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - import
  - '@typescript-eslint'

globals:
  fetch: false
  __DEV__: readonly

settings:
  import/ignore:
    - react
  import/no-extraneous-dependencies:
    - error
  import/resolver:
    node:
      paths:
        - ./
      moduleDirectory:
        - node_modules

rules:
  # React Rules
  react/prop-types: off
  react/no-unused-prop-types: off
  react/no-unused-state: off
  react/prefer-stateless-function: warn
  react/forbid-prop-types: [off, { forbid: [] }]
  react/require-default-props: off
  react/jsx-sort-props:
    - error
    - callbacksLast: true
      shorthandFirst: true
      shorthandLast: false
      ignoreCase: false
      noSortAlphabetically: false
      reservedFirst: true

  react-hooks/exhaustive-deps: off

  # Import Rules
  import/extensions:
    - 1
    - never
    - svg: always
      json: always
      fragments: always
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
      optionalDependencies: false
      peerDependencies: false
  import/prefer-default-export: off
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  import/order:
    - error
    # note settings['import/internal-regex'] above
    - groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
      alphabetize:
        order: "asc"
      newlines-between: always
      pathGroups:
        - pattern: react
          group: builtin
          position: after
        - pattern: .*/**/*.css
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react

  # General Rules
  semi:
    - off
  comma-dangle: off
  operator-linebreak:
    - off
    - before
    - overrides:
        '=': ignore
  no-console: warn
  no-plusplus: off
  no-nested-ternary: off
  arrow-body-style: off
  consistent-return: off
  curly:
    - error
    - all
  implicit-arrow-linebreak: off

  # for post defining style object in react-native
  no-use-before-define: off
  '@typescript-eslint/semi':
    - error
    - never
  '@typescript-eslint/no-use-before-define':
    - error
    - variables: false
      functions: false
  '@typescript-eslint/explicit-module-boundary-types': off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  '@typescript-eslint/no-empty-function': warn
