---
exclude: >
      (?x)(
          \\.dist-info |
          build
      )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-json
      - id: mixed-line-ending
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-d=relaxed]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=105]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--filter-files]
        files: \.py$
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: local
    hooks:
      - id: mypy-pipenv
        name: mypy-pipenv
        entry: pipenv run mypy app
        language: system
        pass_filenames: false
        types: [python]
        args:
          - --show-traceback
